# Catálogo de variables para APE1 (Panel de América Latina)
# Centralizado para evitar duplicación en scripts.

SERIES_APE1 = [
    {
        "nombre_raw":     "forest_area_km2",
        "codigo_api":     "AG.LND.FRST.K2",
        "unidad_api":     "km²",
        "fuente":         "World Bank WDI",
        "institucion":    "World Bank / FAO",
        "url_indicador":  "https://data.worldbank.org/indicator/AG.LND.FRST.K2",
        "rol":            "dependiente — ambiental",
        "concepto":       "Superficie forestal total",
    },
    {
        "nombre_raw":     "ghg_total_incl_lulucf_mt_co2e",
        "codigo_api":     "EN.GHG.ALL.LU.MT.CE.AR5",
        "unidad_api":     "Mt CO2 equivalente",
        "fuente":         "World Bank WDI / EDGAR",
        "institucion":    "World Bank / JRC",
        "url_indicador":  "https://data.worldbank.org/indicator/EN.GHG.ALL.LU.MT.CE.AR5",
        "rol":            "dependiente — ambiental",
        "concepto":       "Emisiones de GEI totales con LULUCF",
    },
    {
        "nombre_raw":     "gdp_per_capita_const2015_usd",
        "codigo_api":     "NY.GDP.PCAP.KD",
        "unidad_api":     "USD constantes 2015",
        "fuente":         "World Bank WDI",
        "institucion":    "World Bank",
        "url_indicador":  "https://data.worldbank.org/indicator/NY.GDP.PCAP.KD",
        "rol":            "independiente — económica",
        "concepto":       "PIB per cápita (Crecimiento)",
    },
    {
        "nombre_raw":     "trade_pct_gdp",
        "codigo_api":     "NE.TRD.GNFS.ZS",
        "unidad_api":     "% del PIB",
        "fuente":         "World Bank WDI",
        "institucion":    "World Bank",
        "url_indicador":  "https://data.worldbank.org/indicator/NE.TRD.GNFS.ZS",
        "rol":            "independiente — apertura",
        "concepto":       "Apertura comercial (Expo+Impo)",
    },
    {
        "nombre_raw":     "fdi_inflows_pct_gdp",
        "codigo_api":     "BX.KLT.DINV.WD.GD.ZS",
        "unidad_api":     "% del PIB",
        "fuente":         "World Bank WDI / FMI",
        "institucion":    "World Bank / FMI",
        "url_indicador":  "https://data.worldbank.org/indicator/BX.KLT.DINV.WD.GD.ZS",
        "rol":            "independiente — inversión",
        "concepto":       "Inversión Extranjera Directa (IED)",
    },
    {
        "nombre_raw":     "renewable_energy_pct_final_energy",
        "codigo_api":     "EG.FEC.RNEW.ZS",
        "unidad_api":     "% del consumo total",
        "fuente":         "World Bank WDI / IEA",
        "institucion":    "World Bank / IEA",
        "url_indicador":  "https://data.worldbank.org/indicator/EG.FEC.RNEW.ZS",
        "rol":            "control — tecnología verde",
        "concepto":       "Consumo de energía renovable",
    },
    {
        "nombre_raw":     "domestic_credit_private_pct_gdp",
        "codigo_api":     "FS.AST.PRVT.GD.ZS",
        "unidad_api":     "% del PIB",
        "fuente":         "World Bank WDI / FMI",
        "institucion":    "World Bank / FMI",
        "url_indicador":  "https://data.worldbank.org/indicator/FS.AST.PRVT.GD.ZS",
        "rol":            "control — financiero",
        "concepto":       "Profundidad financiera (Crédito privado)",
    },
    {
        "nombre_raw":     "wgi_voice_accountability_est",
        "codigo_api":     "GOV_WGI_VA.EST",
        "unidad_api":     "Índice -2.5 a +2.5",
        "fuente":         "World Bank WGI",
        "institucion":    "World Bank",
        "url_indicador":  "https://www.worldbank.org/en/publication/worldwide-governance-indicators",
        "rol":            "control — gobernanza",
        "concepto":       "Rendición de cuentas y voz",
    },
    {
        "nombre_raw":     "co2_emissions_kt",
        "codigo_api":     "EN.ATM.CO2E.KT",
        "unidad_api":     "kt de CO2",
        "fuente":         "World Bank WDI",
        "institucion":    "World Bank",
        "url_indicador":  "https://data.worldbank.org/indicator/EN.ATM.CO2E.KT",
        "rol":            "dependiente — ambiental",
        "concepto":       "Emisiones de CO2 totales",
    },
    {
        "nombre_raw":     "informal_employment_pct_total",
        "codigo_api":     "SL.ISV.IFRM.ZS",
        "unidad_api":     "% del empleo total",
        "fuente":         "World Bank / ILO",
        "institucion":    "ILO (International Labour Organization)",
        "url_indicador":  "https://data.worldbank.org/indicator/SL.ISV.IFRM.ZS",
        "rol":            "independiente — laboral",
        "concepto":       "Empleo informal como % del empleo total",
    },
    {
        "nombre_raw":     "ecu_informal_sector_inec",
        "codigo_api":     "LOCAL_ENEMDU_INF",
        "unidad_api":     "Porcentaje (%)",
        "fuente":         "INEC ENEMDU",
        "institucion":    "Instituto Nacional de Estadística y Censos (Ecuador)",
        "url_indicador":  "https://www.ecuadorencifras.gob.ec/estadisticas-laborales-enemdu/",
        "rol":            "objetivo — informalidad",
        "concepto":       "Empleo en el sector informal (Falta de RUC en el establecimiento)",
        "scope":          "ecuador_local",
        "source_kind":    "local_csv",
    },
]

PAISES_LATAM = {
    "AR": "Argentina",  "BO": "Bolivia",    "BR": "Brasil",
    "CL": "Chile",      "CO": "Colombia",   "CR": "Costa Rica",
    "CU": "Cuba",       "EC": "Ecuador",    "SV": "El Salvador",
    "GT": "Guatemala",  "HT": "Haití",      "HN": "Honduras",
    "MX": "México",     "NI": "Nicaragua",  "PA": "Panamá",
    "PY": "Paraguay",   "PE": "Perú",       "DO": "República Dominicana",
    "UY": "Uruguay",    "VE": "Venezuela",
}
