project:
  type: default
  output-dir: _book

metadata:
  university: "UNIVERSIDAD NACIONAL DE LOJA"
  faculty: "FACULTAD JURÍDICA, SOCIAL Y ADMINISTRATIVA"
  school: "CARRERA DE ECONOMÍA"
  professor: "Econ. Jose Rafael Alvarado Lopez"
  year: "2026"

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
    papersize: letter
    pdf-engine: lualatex
    geometry:
      - top=2.54cm
      - bottom=2.54cm
      - left=2.54cm
      - right=2.54cm
    fontfamily: times
    fontsize: 12pt
    linestretch: 1.5
    toc: true
    number-sections: true
    indent: true
    fig-width: 2.8
    fig-height: 1.8
    fig-align: center
    include-in-header:
      text: |
        \makeatletter
        \def\pandocbounded#1{#1}
        \makeatother

crossref:
  tbl-prefix: "Tabla"
  fig-prefix: "Figura"
